name: statping
version-script: cat version.txt
version: "stable"
summary: Statping Server Monitoring with Status Page
description: >
  An easy to use Status Page for your websites and applications.
  Statping will automatically fetch the application and render a beautiful
  status page with tons of features for you to build an even better status page.
  This Status Page generator allows you to use MySQL, Postgres, or SQLite
  on multiple operating systems.

type: app
confinement: strict
grade: stable

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
  - build-on: i386

apps:
  statping:
    command: statping
    plugs:
      - home
      - network
      - network-bind

parts:
  statping:
    source: .
    plugin: nil
    override-build: |
      apt-get update
      apt-get install -y curl
      curl -o- -L https://statping.com/install.sh | bash
      mv /usr/local/bin/statping ./
    build-packages:
      - git
      - gcc
      - make
      - sed
