FROM node:10.17.0-alpine AS frontend
RUN npm install yarn -g

#Backend

#Configure Go
RUN echo "installing go" 
RUN apk add --no-cache --virtual .build-deps bash openssl go 
RUN apk add libc-dev gcc musl-dev
RUN wget -O go.tgz https://golang.org/dl/go1.14.6.src.tar.gz 
RUN tar -C /usr/local -xzf go.tgz 
WORKDIR /usr/local/go/src/ 
RUN ./make.bash 
ENV PATH="/usr/local/go/bin:$PATH"
ENV GOPATH=/opt/go/ 
ENV PATH=$PATH:$GOPATH/bin 
RUN apk del .build-deps 
RUN go version

WORKDIR /go/src/github.com/torusresearch/statping
ADD go.mod go.sum version.txt ./

RUN go mod download

RUN go get github.com/stretchr/testify/... && \
	go get github.com/GeertJohan/go.rice/rice && \
	go get github.com/cortesi/modd/cmd/modd
ENV IS_DOCKER=true
ENV STATPING_DIR=/go/src/github.com/torusresearch/statping
EXPOSE 8585
EXPOSE 8888
# COPY . .

CMD dev/dev-env.sh